export interface ApiEndpoint {
  method: "POST";
  path: string;
  category: string;
  description: string;
  requiredParams: string[];
  optionalParams?: string[];
  exampleBody?: string;
}

export const INTERNAL_LINEAR_API_ENDPOINTS: ApiEndpoint[] = [
  {
    method: "POST",
    path: "/internal/linear/comment",
    category: "comments",
    description: "在 issue 上添加评论",
    requiredParams: ["workspaceId", "issueId", "body"],
    exampleBody: `{
  "workspaceId": "ws_abc123",
  "issueId": "ISSUE_ID",
  "body": "这是一条评论"
}`,
  },
  {
    method: "POST",
    path: "/internal/linear/comments/update",
    category: "comments",
    description: "更新评论",
    requiredParams: ["workspaceId", "id", "body"],
    exampleBody: `{
  "workspaceId": "ws_abc123",
  "id": "COMMENT_ID",
  "body": "更新后的评论"
}`,
  },
  {
    method: "POST",
    path: "/internal/linear/comments/delete",
    category: "comments",
    description: "删除评论",
    requiredParams: ["workspaceId", "id"],
  },
  {
    method: "POST",
    path: "/internal/linear/comments/resolve",
    category: "comments",
    description: "解决评论线程",
    requiredParams: ["workspaceId", "id"],
  },
  {
    method: "POST",
    path: "/internal/linear/comments/unresolve",
    category: "comments",
    description: "重新打开评论线程",
    requiredParams: ["workspaceId", "id"],
  },
  {
    method: "POST",
    path: "/internal/linear/issues/create",
    category: "issues",
    description: "创建新的 issue",
    requiredParams: ["workspaceId", "teamId", "title"],
    optionalParams: ["description", "projectId", "parentId"],
  },
  {
    method: "POST",
    path: "/internal/linear/issues/update",
    category: "issues",
    description: "更新 issue 信息",
    requiredParams: ["workspaceId", "issueId"],
    optionalParams: ["title", "description", "projectId"],
  },
  {
    method: "POST",
    path: "/internal/linear/issues/assign",
    category: "issues",
    description: "分配 issue 给某人",
    requiredParams: ["workspaceId", "issueId", "assigneeId"],
  },
  {
    method: "POST",
    path: "/internal/linear/issues/state",
    category: "issues",
    description: "改变 issue 状态",
    requiredParams: ["workspaceId", "issueId", "stateId"],
  },
  {
    method: "POST",
    path: "/internal/linear/issues/project",
    category: "issues",
    description: "将 issue 添加到项目",
    requiredParams: ["workspaceId", "issueId", "projectId"],
  },
  {
    method: "POST",
    path: "/internal/linear/issues/archive",
    category: "issues",
    description: "归档 issue",
    requiredParams: ["workspaceId", "id"],
  },
  {
    method: "POST",
    path: "/internal/linear/issues/delete",
    category: "issues",
    description: "删除 issue",
    requiredParams: ["workspaceId", "id"],
  },
  {
    method: "POST",
    path: "/internal/linear/issues/get",
    category: "issues",
    description: "获取 issue 详情",
    requiredParams: ["workspaceId", "identifier"],
  },
  {
    method: "POST",
    path: "/internal/linear/issues/children",
    category: "issues",
    description: "获取子 issue 列表",
    requiredParams: ["workspaceId", "issueId"],
    optionalParams: ["first"],
  },
  {
    method: "POST",
    path: "/internal/linear/issues/attachment",
    category: "attachments",
    description: "添加附件",
    requiredParams: ["workspaceId", "issueId", "title", "url"],
  },
  {
    method: "POST",
    path: "/internal/linear/attachments/delete",
    category: "attachments",
    description: "删除附件",
    requiredParams: ["workspaceId", "id"],
  },
  {
    method: "POST",
    path: "/internal/linear/issues/relation",
    category: "relations",
    description: "创建 issue 关系",
    requiredParams: ["workspaceId", "issueId", "relatedIssueId", "relationType"],
  },
  {
    method: "POST",
    path: "/internal/linear/issues/list",
    category: "issues",
    description: "按编号批量列出 issue",
    requiredParams: ["workspaceId", "teamId", "numbers"],
  },
  {
    method: "POST",
    path: "/internal/linear/team/states",
    category: "team",
    description: "列出团队状态",
    requiredParams: ["workspaceId", "teamId"],
  },
  {
    method: "POST",
    path: "/internal/linear/team/projects",
    category: "projects",
    description: "列出团队项目简表",
    requiredParams: ["workspaceId", "teamId"],
  },
  {
    method: "POST",
    path: "/internal/linear/projects/list",
    category: "projects",
    description: "列出项目",
    requiredParams: ["workspaceId", "teamId"],
  },
  {
    method: "POST",
    path: "/internal/linear/projects/get",
    category: "projects",
    description: "获取项目详情",
    requiredParams: ["workspaceId", "projectId"],
  },
  {
    method: "POST",
    path: "/internal/linear/projects/create",
    category: "projects",
    description: "创建项目",
    requiredParams: ["workspaceId", "teamId", "name"],
    optionalParams: ["description"],
  },
  {
    method: "POST",
    path: "/internal/linear/projects/update",
    category: "projects",
    description: "更新项目",
    requiredParams: ["workspaceId", "projectId"],
    optionalParams: ["name", "description"],
  },
  {
    method: "POST",
    path: "/internal/linear/projects/delete",
    category: "projects",
    description: "归档项目",
    requiredParams: ["workspaceId", "projectId"],
  },
  {
    method: "POST",
    path: "/internal/linear/triage/list",
    category: "triage",
    description: "列出 triage 队列",
    requiredParams: ["workspaceId", "teamId"],
    optionalParams: ["stateName", "excludeDone", "excludeCancelled", "limit"],
  },
  {
    method: "POST",
    path: "/internal/linear/triage/move",
    category: "triage",
    description: "处理 triage issue",
    requiredParams: ["workspaceId", "issueId"],
    optionalParams: ["assigneeId", "stateId", "projectId"],
  },
  {
    method: "POST",
    path: "/internal/linear/initiatives/list",
    category: "initiatives",
    description: "列出 initiatives",
    requiredParams: ["workspaceId"],
    optionalParams: ["limit"],
  },
  {
    method: "POST",
    path: "/internal/linear/initiatives/get",
    category: "initiatives",
    description: "获取 initiative 详情",
    requiredParams: ["workspaceId", "id"],
  },
  {
    method: "POST",
    path: "/internal/linear/initiatives/create",
    category: "initiatives",
    description: "创建 initiative",
    requiredParams: ["workspaceId", "name"],
    optionalParams: ["description", "status"],
  },
  {
    method: "POST",
    path: "/internal/linear/initiatives/update",
    category: "initiatives",
    description: "更新 initiative",
    requiredParams: ["workspaceId", "id"],
    optionalParams: ["name", "description", "status"],
  },
  {
    method: "POST",
    path: "/internal/linear/initiatives/archive",
    category: "initiatives",
    description: "归档 initiative",
    requiredParams: ["workspaceId", "id"],
  },
  {
    method: "POST",
    path: "/internal/linear/cycles/list",
    category: "cycles",
    description: "列出 cycles",
    requiredParams: ["workspaceId", "teamId"],
    optionalParams: ["limit"],
  },
  {
    method: "POST",
    path: "/internal/linear/cycles/get",
    category: "cycles",
    description: "获取 cycle 详情",
    requiredParams: ["workspaceId", "id"],
  },
  {
    method: "POST",
    path: "/internal/linear/cycles/create",
    category: "cycles",
    description: "创建 cycle",
    requiredParams: ["workspaceId", "teamId", "startsAt", "endsAt"],
    optionalParams: ["name"],
  },
  {
    method: "POST",
    path: "/internal/linear/cycles/update",
    category: "cycles",
    description: "更新 cycle",
    requiredParams: ["workspaceId", "id"],
    optionalParams: ["startsAt", "endsAt", "name"],
  },
  {
    method: "POST",
    path: "/internal/linear/cycles/archive",
    category: "cycles",
    description: "归档 cycle",
    requiredParams: ["workspaceId", "id"],
  },
  {
    method: "POST",
    path: "/internal/linear/labels/list",
    category: "labels",
    description: "列出标签",
    requiredParams: ["workspaceId"],
    optionalParams: ["limit"],
  },
  {
    method: "POST",
    path: "/internal/linear/labels/get",
    category: "labels",
    description: "获取标签详情",
    requiredParams: ["workspaceId", "id"],
  },
  {
    method: "POST",
    path: "/internal/linear/labels/create",
    category: "labels",
    description: "创建标签",
    requiredParams: ["workspaceId", "name"],
    optionalParams: ["color", "description"],
  },
  {
    method: "POST",
    path: "/internal/linear/labels/update",
    category: "labels",
    description: "更新标签",
    requiredParams: ["workspaceId", "id"],
    optionalParams: ["name", "color", "description"],
  },
  {
    method: "POST",
    path: "/internal/linear/labels/retire",
    category: "labels",
    description: "停用标签",
    requiredParams: ["workspaceId", "id"],
  },
  {
    method: "POST",
    path: "/internal/linear/labels/restore",
    category: "labels",
    description: "恢复标签",
    requiredParams: ["workspaceId", "id"],
  },
  {
    method: "POST",
    path: "/internal/linear/documents/list",
    category: "documents",
    description: "列出文档",
    requiredParams: ["workspaceId"],
    optionalParams: ["limit", "issueId", "projectId", "initiativeId"],
  },
  {
    method: "POST",
    path: "/internal/linear/documents/get",
    category: "documents",
    description: "获取文档详情",
    requiredParams: ["workspaceId", "id"],
  },
  {
    method: "POST",
    path: "/internal/linear/documents/create",
    category: "documents",
    description: "创建文档",
    requiredParams: ["workspaceId", "title"],
    optionalParams: ["content", "issueId", "projectId", "initiativeId", "icon", "color"],
  },
  {
    method: "POST",
    path: "/internal/linear/documents/update",
    category: "documents",
    description: "更新文档",
    requiredParams: ["workspaceId", "id"],
    optionalParams: ["title", "content", "icon", "color"],
  },
  {
    method: "POST",
    path: "/internal/linear/documents/delete",
    category: "documents",
    description: "删除文档",
    requiredParams: ["workspaceId", "id"],
  },
  {
    method: "POST",
    path: "/internal/linear/documents/unarchive",
    category: "documents",
    description: "恢复文档",
    requiredParams: ["workspaceId", "id"],
  },
  {
    method: "POST",
    path: "/internal/linear/customers/list",
    category: "customers",
    description: "列出客户",
    requiredParams: ["workspaceId"],
    optionalParams: ["limit"],
  },
  {
    method: "POST",
    path: "/internal/linear/customers/get",
    category: "customers",
    description: "获取客户详情",
    requiredParams: ["workspaceId", "id"],
  },
  {
    method: "POST",
    path: "/internal/linear/customers/create",
    category: "customers",
    description: "创建客户",
    requiredParams: ["workspaceId", "name"],
    optionalParams: ["domains", "revenue", "size"],
  },
  {
    method: "POST",
    path: "/internal/linear/customers/update",
    category: "customers",
    description: "更新客户",
    requiredParams: ["workspaceId", "id"],
    optionalParams: ["name", "domains", "revenue", "size"],
  },
  {
    method: "POST",
    path: "/internal/linear/customers/delete",
    category: "customers",
    description: "删除客户",
    requiredParams: ["workspaceId", "id"],
  },
  {
    method: "POST",
    path: "/internal/linear/customer-needs/list",
    category: "customer-needs",
    description: "列出客户需求",
    requiredParams: ["workspaceId"],
    optionalParams: ["limit"],
  },
  {
    method: "POST",
    path: "/internal/linear/customer-needs/get",
    category: "customer-needs",
    description: "获取客户需求详情",
    requiredParams: ["workspaceId", "id"],
  },
  {
    method: "POST",
    path: "/internal/linear/customer-needs/create",
    category: "customer-needs",
    description: "创建客户需求",
    requiredParams: ["workspaceId", "body"],
    optionalParams: ["customerId", "issueId", "projectId", "priority"],
  },
  {
    method: "POST",
    path: "/internal/linear/customer-needs/update",
    category: "customer-needs",
    description: "更新客户需求",
    requiredParams: ["workspaceId", "id"],
    optionalParams: ["body", "customerId", "issueId", "projectId", "priority"],
  },
  {
    method: "POST",
    path: "/internal/linear/customer-needs/delete",
    category: "customer-needs",
    description: "归档客户需求",
    requiredParams: ["workspaceId", "id"],
  },
  {
    method: "POST",
    path: "/internal/linear/customer-needs/unarchive",
    category: "customer-needs",
    description: "恢复客户需求",
    requiredParams: ["workspaceId", "id"],
  },
  {
    method: "POST",
    path: "/internal/linear/project-updates/list",
    category: "project-updates",
    description: "列出项目周报",
    requiredParams: ["workspaceId"],
    optionalParams: ["limit"],
  },
  {
    method: "POST",
    path: "/internal/linear/project-updates/get",
    category: "project-updates",
    description: "获取项目周报详情",
    requiredParams: ["workspaceId", "id"],
  },
  {
    method: "POST",
    path: "/internal/linear/project-updates/create",
    category: "project-updates",
    description: "创建项目周报",
    requiredParams: ["workspaceId", "projectId", "body"],
    optionalParams: ["health"],
  },
  {
    method: "POST",
    path: "/internal/linear/project-updates/update",
    category: "project-updates",
    description: "更新项目周报",
    requiredParams: ["workspaceId", "id"],
    optionalParams: ["body", "health"],
  },
  {
    method: "POST",
    path: "/internal/linear/project-updates/delete",
    category: "project-updates",
    description: "归档项目周报",
    requiredParams: ["workspaceId", "id"],
  },
  {
    method: "POST",
    path: "/internal/linear/project-updates/unarchive",
    category: "project-updates",
    description: "恢复项目周报",
    requiredParams: ["workspaceId", "id"],
  },
  {
    method: "POST",
    path: "/internal/linear/workflow-states/list",
    category: "workflow-states",
    description: "列出工作流状态",
    requiredParams: ["workspaceId", "teamId"],
    optionalParams: ["limit"],
  },
  {
    method: "POST",
    path: "/internal/linear/workflow-states/get",
    category: "workflow-states",
    description: "获取工作流状态详情",
    requiredParams: ["workspaceId", "id"],
  },
  {
    method: "POST",
    path: "/internal/linear/workflow-states/create",
    category: "workflow-states",
    description: "创建工作流状态",
    requiredParams: ["workspaceId", "teamId", "name", "type"],
    optionalParams: ["position"],
  },
  {
    method: "POST",
    path: "/internal/linear/workflow-states/update",
    category: "workflow-states",
    description: "更新工作流状态",
    requiredParams: ["workspaceId", "id"],
    optionalParams: ["name", "type", "position"],
  },
  {
    method: "POST",
    path: "/internal/linear/workflow-states/archive",
    category: "workflow-states",
    description: "归档工作流状态",
    requiredParams: ["workspaceId", "id"],
  },
  {
    method: "POST",
    path: "/internal/linear/resolve",
    category: "team",
    description: "解析 team key 到 workspaceId/teamId",
    requiredParams: ["teamKey", "workspaceId"],
  },
  {
    method: "POST",
    path: "/internal/linear/search",
    category: "search",
    description: "统一搜索 issues、documents、projects、customers、customer-needs、project-updates 与 triage。",
    requiredParams: ["workspaceId", "scope"],
    optionalParams: ["teamId", "query", "project", "state", "assignee", "label", "customer", "limit"],
    exampleBody: `{
  "workspaceId": "ws_abc123",
  "teamId": "team_abc123",
  "scope": "issues",
  "query": "oauth timeout",
  "state": "In Progress",
  "limit": 10
}`,
  },
];
